### ISSUE TITLE
websocket fails "Invalid frame header"

### ISSUE THREAD

**Issue by haakondr** [NIVANorge/watexr_voila_app#4]
Occationally get this issue when trying to access the application, causing no dropdown boxes to be shown. This seems to happen when websocket traffic fails.

## environment

- accessing the deployed application at https://watexr.test.niva.no/
- browser: google-chrome 85.0.4183.102 linux/ubuntu

## error

the request wss://watexr.test.niva.no/api/kernels/ea77bb8b-43c5-4a90-b2d1-72644bb57959/channels?session_id=2089a130-9d39-4d1c-8776-54755c808249 receives the following error:

{"buffers":[],"channel":"shell","content":{},"header":{"date":"2020-09-17T07:30:00.934Z","msg_id":"e0e9db6e-3ed5-43ce-8eaf-db4ea11cb2f0","msg_type":"kernel_info_request","session":"2089a130-9d39-4d1c-8776-54755c808249","username":"","version":"5.2"},"metadata":{},"parent_header":{}} | 283 | 09:30:00.934
-- | -- | --
Invalid frame header | N/A | 09:30:00.934

javascript console:

```
Starting WebSocket: wss://watexr.test.niva.no/api/kernels/ea77bb8b-43c5-4a90-b2d1-72644bb57959
favicon.ico:1 GET https://watexr.test.niva.no/voila/files/favicon.ico 403
default.js:1452 Kernel: connected (ea77bb8b-43c5-4a90-b2d1-72644bb57959)
default.js:64 WebSocket connection to 'wss://watexr.test.niva.no/api/kernels/ea77bb8b-43c5-4a90-b2d1-72644bb57959/channels?session_id=2089a130-9d39-4d1c-8776-54755c808249' failed: Invalid frame header

default.js:56 Starting WebSocket: wss://watexr.test.niva.no/api/kernels/ea77bb8b-43c5-4a90-b2d1-72644bb57959
default.js:64 WebSocket connection to 'wss://watexr.test.niva.no/api/kernels/ea77bb8b-43c5-4a90-b2d1-72644bb57959/channels?session_id=2089a130-9d39-4d1c-8776-54755c808249' failed: Error during WebSocket handshake: Unexpected response code: 404

default.js:56 Starting WebSocket: wss://watexr.test.niva.no/api/kernels/ea77bb8b-43c5-4a90-b2d1-72644bb57959
default.js:1452 Kernel: connected (ea77bb8b-43c5-4a90-b2d1-72644bb57959)
 ```

It failed at first, but then succeeded at the second attempt. After this, the application was working. I suspect something similar is happening on ios chrome, but then it never works

**Comment by JamesSample** [comment]
This error seems more persistent now, not sure why. Attempting to access the app over the past few days always gives

`default.js:64 WebSocket connection to 'wss://watexr.test.niva.no/api/kernels/a872f647-1825-4120-8bf6-648f494fdfd2/channels?session_id=6827471f-0b4d-4fe1-a4b5-e4b655dff45a' failed: Error during WebSocket handshake: Unexpected response code: 404`

Even on desktop computers using Chrome. Strange that it was working fine initially!

**Comment by haakondr** [comment]
I have trouble reproducing this now, seems to "just work". 

what chrome version are you using?

also, you seem to be getting a different error than what I was getting

**Comment by haakondr** [comment]
```
$ kubectl get pods | grep watex
watexr-5cbc8756b9-kb7c5                  1/1     Running     0          17h
```

JamesSample commented **17 hours ago**

The pod has been running for 17 hours. Assuming that this happened when you commented, this must be the cause. 

Looking at the logs, we had a restart at 2020-10-05 14:16:43.000 CEST

https://console.cloud.google.com/logs/query;query=jsonPayload.kind%3D%22Event%22%0AjsonPayload.involvedObject.fieldPath%3D%22spec.containers%7Bwatexr%7D%22;timeRange=P2D;summaryFields=resource%252Flabels%252Fpod_name:false:32:beginning?scrollTimestamp=2020-10-05T12:24:07.383000585Z&authuser=1&organizationId=1082479656149&project=nivatest-1

I see that the deployment is running on kubernetes node pool  "pool-1". This one is poorly named, but it is a group of virtual machines that are "preemtible". Preemtible VM's are cheaper machines that restart every 24h and is not well suited for running web applications as they can be shutdown at any time. This could be the cause of the issues you are seeing.
